"""Avatar clothes catalog — shirts & hats bought with coins."""

DEFAULT_SHIRT = "tee_plain"
DEFAULT_HAT = "hat_none"
DEFAULT_PANTS = "pants_green"
DEFAULT_NAME = "name_plain"

SLOT_COLUMNS = {
    "shirt": "equipped_shirt",
    "pants": "equipped_pants",
    "hat": "equipped_hat",
    "name": "equipped_name",
}


def slot_column(slot: str) -> str:
    return SLOT_COLUMNS.get(slot, "equipped_hat")


ADMIN_OWNER_LIMIT = 2
# 1 quadrillion — owner / Admin set cap (1 qt)
ADMIN_COST = 1_000_000_000_000_000
ADMIN_ITEM_IDS = ("tee_admin", "pants_admin", "acc_admin")

# Lots of cloth for the marketplace. One flex shirt at 1,000,000 coins.
MARKET_ITEMS = (
    # Starter
    {
        "id": "tee_plain",
        "slot": "shirt",
        "label": "White Shirt",
        "cost": 0,
        "emoji": "👕",
        "color": "#f8fafc",
        "accent": "#cbd5e1",
        "pattern": "solid",
        "badge": "",
        "blurb": "Your first shirt — free!",
    },
    # Common color tees
    {
        "id": "tee_red",
        "slot": "shirt",
        "label": "Red Shirt",
        "cost": 40,
        "emoji": "👕",
        "color": "#dc2626",
        "accent": "#991b1b",
        "pattern": "solid",
        "badge": "",
        "blurb": "Bright red tee",
    },
    {
        "id": "tee_blue",
        "slot": "shirt",
        "label": "Blue Shirt",
        "cost": 40,
        "emoji": "👕",
        "color": "#2563eb",
        "accent": "#1e3a8a",
        "pattern": "solid",
        "badge": "",
        "blurb": "Cool blue tee",
    },
    {
        "id": "tee_green",
        "slot": "shirt",
        "label": "Green Shirt",
        "cost": 40,
        "emoji": "👕",
        "color": "#16a34a",
        "accent": "#166534",
        "pattern": "solid",
        "badge": "",
        "blurb": "Fresh green tee",
    },
    {
        "id": "tee_yellow",
        "slot": "shirt",
        "label": "Yellow Shirt",
        "cost": 60,
        "emoji": "👕",
        "color": "#eab308",
        "accent": "#a16207",
        "pattern": "solid",
        "badge": "",
        "blurb": "Sunny yellow tee",
    },
    {
        "id": "tee_pink",
        "slot": "shirt",
        "label": "Pink Shirt",
        "cost": 60,
        "emoji": "👕",
        "color": "#db2777",
        "accent": "#9d174d",
        "pattern": "solid",
        "badge": "",
        "blurb": "Sweet pink tee",
    },
    {
        "id": "tee_orange",
        "slot": "shirt",
        "label": "Orange Shirt",
        "cost": 60,
        "emoji": "👕",
        "color": "#ea580c",
        "accent": "#9a3412",
        "pattern": "solid",
        "badge": "",
        "blurb": "Warm orange tee",
    },
    {
        "id": "tee_purple",
        "slot": "shirt",
        "label": "Purple Shirt",
        "cost": 80,
        "emoji": "👕",
        "color": "#7c3aed",
        "accent": "#5b21b6",
        "pattern": "solid",
        "badge": "",
        "blurb": "Magic purple tee",
    },
    {
        "id": "tee_black",
        "slot": "shirt",
        "label": "Night Shirt",
        "cost": 80,
        "emoji": "👕",
        "color": "#1e293b",
        "accent": "#0f172a",
        "pattern": "solid",
        "badge": "",
        "blurb": "Dark night tee",
    },
    {
        "id": "tee_sky",
        "slot": "shirt",
        "label": "Sky Shirt",
        "cost": 90,
        "emoji": "👕",
        "color": "#38bdf8",
        "accent": "#0284c7",
        "pattern": "solid",
        "badge": "",
        "blurb": "Soft sky blue",
    },
    # Patterns
    {
        "id": "tee_stripe",
        "slot": "shirt",
        "label": "Stripe Shirt",
        "cost": 150,
        "emoji": "👕",
        "color": "#2563eb",
        "accent": "#f8fafc",
        "pattern": "stripe",
        "badge": "",
        "blurb": "Blue and white stripes",
    },
    {
        "id": "tee_dots",
        "slot": "shirt",
        "label": "Dot Shirt",
        "cost": 150,
        "emoji": "👕",
        "color": "#db2777",
        "accent": "#fce7f3",
        "pattern": "dots",
        "badge": "",
        "blurb": "Pink with dots",
    },
    {
        "id": "tee_star",
        "slot": "shirt",
        "label": "Star Shirt",
        "cost": 250,
        "emoji": "⭐",
        "color": "#7c3aed",
        "accent": "#fbbf24",
        "pattern": "solid",
        "badge": "⭐",
        "blurb": "A star on your chest",
    },
    {
        "id": "tee_heart",
        "slot": "shirt",
        "label": "Heart Shirt",
        "cost": 250,
        "emoji": "❤️",
        "color": "#fce7f3",
        "accent": "#db2777",
        "pattern": "solid",
        "badge": "❤️",
        "blurb": "A big heart tee",
    },
    {
        "id": "tee_rainbow",
        "slot": "shirt",
        "label": "Rainbow Shirt",
        "cost": 400,
        "emoji": "🌈",
        "color": "#7c3aed",
        "accent": "#22c55e",
        "pattern": "rainbow",
        "badge": "🌈",
        "blurb": "Every color at once",
    },
    {
        "id": "tee_soccer",
        "slot": "shirt",
        "label": "Soccer Shirt",
        "cost": 500,
        "emoji": "⚽",
        "color": "#16a34a",
        "accent": "#f8fafc",
        "pattern": "stripe",
        "badge": "⚽",
        "blurb": "Play like a star",
    },
    {
        "id": "tee_cat",
        "slot": "shirt",
        "label": "Cat Shirt",
        "cost": 600,
        "emoji": "🐱",
        "color": "#fdba74",
        "accent": "#9a3412",
        "pattern": "solid",
        "badge": "🐱",
        "blurb": "Meow on your shirt",
    },
    {
        "id": "tee_dog",
        "slot": "shirt",
        "label": "Dog Shirt",
        "cost": 600,
        "emoji": "🐶",
        "color": "#93c5fd",
        "accent": "#1d4ed8",
        "pattern": "solid",
        "badge": "🐶",
        "blurb": "Woof woof tee",
    },
    {
        "id": "tee_rocket",
        "slot": "shirt",
        "label": "Rocket Shirt",
        "cost": 800,
        "emoji": "🚀",
        "color": "#0f172a",
        "accent": "#38bdf8",
        "pattern": "solid",
        "badge": "🚀",
        "blurb": "Blast off",
    },
    {
        "id": "tee_dragon",
        "slot": "shirt",
        "label": "Dragon Shirt",
        "cost": 1200,
        "emoji": "🐉",
        "color": "#14532d",
        "accent": "#22c55e",
        "pattern": "solid",
        "badge": "🐉",
        "blurb": "Fierce dragon tee",
    },
    {
        "id": "tee_ice",
        "slot": "shirt",
        "label": "Ice Shirt",
        "cost": 1500,
        "emoji": "❄️",
        "color": "#e0f2fe",
        "accent": "#0284c7",
        "pattern": "dots",
        "badge": "❄️",
        "blurb": "Icy cool",
    },
    {
        "id": "tee_fire",
        "slot": "shirt",
        "label": "Fire Shirt",
        "cost": 1500,
        "emoji": "🔥",
        "color": "#9a3412",
        "accent": "#fbbf24",
        "pattern": "solid",
        "badge": "🔥",
        "blurb": "Hot like fire",
    },
    {
        "id": "tee_royal",
        "slot": "shirt",
        "label": "Royal Shirt",
        "cost": 5000,
        "emoji": "👑",
        "color": "#4c1d95",
        "accent": "#fbbf24",
        "pattern": "solid",
        "badge": "👑",
        "blurb": "Dress like a king",
    },
    {
        "id": "tee_diamond",
        "slot": "shirt",
        "label": "Diamond Shirt",
        "cost": 25000,
        "emoji": "💎",
        "color": "#082f49",
        "accent": "#67e8f9",
        "pattern": "dots",
        "badge": "💎",
        "blurb": "Shiny rare tee",
    },
    {
        "id": "tee_million",
        "slot": "shirt",
        "label": "Million Shirt",
        "cost": 1_000_000,
        "emoji": "🏆",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "gold",
        "badge": "1M",
        "blurb": "The golden shirt — 1,000,000 coins",
        "legendary": True,
    },
    # Hats
    {
        "id": "hat_none",
        "slot": "hat",
        "label": "No accessory",
        "cost": 0,
        "emoji": "🙂",
        "color": "transparent",
        "accent": "transparent",
        "pattern": "none",
        "badge": "",
        "blurb": "Nothing extra",
        "place": "head",
    },
    {
        "id": "hat_cap",
        "slot": "hat",
        "label": "Blue Cap",
        "cost": 80,
        "emoji": "🧢",
        "color": "#2563eb",
        "accent": "#1d4ed8",
        "pattern": "hat",
        "badge": "",
        "blurb": "A sporty cap",
        "place": "head",
    },
    {
        "id": "hat_beanie",
        "slot": "hat",
        "label": "Beanie",
        "cost": 100,
        "emoji": "🎿",
        "color": "#dc2626",
        "accent": "#991b1b",
        "pattern": "hat",
        "badge": "",
        "blurb": "Warm and cozy",
        "place": "head",
    },
    {
        "id": "hat_flower",
        "slot": "hat",
        "label": "Flower",
        "cost": 200,
        "emoji": "🌸",
        "color": "#f9a8d4",
        "accent": "#db2777",
        "pattern": "hat",
        "badge": "",
        "blurb": "A flower in your hair",
        "place": "head",
    },
    {
        "id": "hat_party",
        "slot": "hat",
        "label": "Party Hat",
        "cost": 300,
        "emoji": "🎉",
        "color": "#7c3aed",
        "accent": "#fbbf24",
        "pattern": "hat",
        "badge": "",
        "blurb": "Party time",
        "place": "head",
    },
    {
        "id": "hat_star",
        "slot": "hat",
        "label": "Star Band",
        "cost": 400,
        "emoji": "⭐",
        "color": "#fbbf24",
        "accent": "#b45309",
        "pattern": "hat",
        "badge": "",
        "blurb": "A star on your head",
        "place": "head",
    },
    {
        "id": "hat_cowboy",
        "slot": "hat",
        "label": "Cowboy Hat",
        "cost": 700,
        "emoji": "🤠",
        "color": "#92400e",
        "accent": "#78350f",
        "pattern": "hat",
        "badge": "",
        "blurb": "Yeehaw",
        "place": "head",
    },
    {
        "id": "hat_crown",
        "slot": "hat",
        "label": "Crown",
        "cost": 2000,
        "emoji": "👑",
        "color": "#fbbf24",
        "accent": "#b45309",
        "pattern": "hat",
        "badge": "",
        "blurb": "You are royalty",
        "place": "head",
    },
    {
        "id": "hat_wizard",
        "slot": "hat",
        "label": "Wizard Hat",
        "cost": 2500,
        "emoji": "🧙",
        "color": "#4c1d95",
        "accent": "#fbbf24",
        "pattern": "hat",
        "badge": "",
        "blurb": "Spell school hat",
        "place": "head",
    },
    {
        "id": "hat_gold",
        "slot": "hat",
        "label": "Gold Medal",
        "cost": 10000,
        "emoji": "🥇",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "hat",
        "badge": "",
        "blurb": "Winner energy",
        "place": "head",
    },
    {
        "id": "acc_glasses",
        "slot": "hat",
        "label": "Cool Glasses",
        "cost": 180,
        "emoji": "🕶️",
        "color": "#0f172a",
        "accent": "#38bdf8",
        "pattern": "hat",
        "badge": "",
        "blurb": "Shades for a rival",
        "place": "face",
    },
    {
        "id": "acc_visor",
        "slot": "hat",
        "label": "Battle Visor",
        "cost": 450,
        "emoji": "🥽",
        "color": "#22c55e",
        "accent": "#14532d",
        "pattern": "hat",
        "badge": "",
        "blurb": "Ready for the arena",
        "place": "face",
    },
    {
        "id": "acc_headphones",
        "slot": "hat",
        "label": "Headphones",
        "cost": 350,
        "emoji": "🎧",
        "color": "#1e293b",
        "accent": "#7c3aed",
        "pattern": "hat",
        "badge": "",
        "blurb": "Hear every footstep",
        "place": "head",
    },
    {
        "id": "acc_backpack",
        "slot": "hat",
        "label": "Backpack",
        "cost": 500,
        "emoji": "🎒",
        "color": "#dc2626",
        "accent": "#7f1d1d",
        "pattern": "hat",
        "badge": "",
        "blurb": "Gear on your back",
        "place": "back",
    },
    {
        "id": "acc_wings",
        "slot": "hat",
        "label": "Wings",
        "cost": 4000,
        "emoji": "🪽",
        "color": "#e0f2fe",
        "accent": "#38bdf8",
        "pattern": "hat",
        "badge": "",
        "blurb": "Fly above the map",
        "place": "back",
    },
    {
        "id": "acc_katana",
        "slot": "hat",
        "label": "Katana",
        "cost": 3500,
        "emoji": "🗡️",
        "color": "#94a3b8",
        "accent": "#0f172a",
        "pattern": "hat",
        "badge": "",
        "blurb": "Rivals melee flex",
        "place": "back",
    },
    {
        "id": "acc_target",
        "slot": "hat",
        "label": "Target Mask",
        "cost": 2200,
        "emoji": "🎯",
        "color": "#ef4444",
        "accent": "#fff",
        "pattern": "hat",
        "badge": "",
        "blurb": "Arena mask",
        "place": "face",
    },
    {
        "id": "acc_goldrank",
        "slot": "hat",
        "label": "Gold Rank",
        "cost": 8000,
        "emoji": "🏅",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "hat",
        "badge": "",
        "blurb": "Show your rank",
        "place": "head",
    },
    # Pants — classic blocky legs (Roblox R6 style)
    {
        "id": "pants_green",
        "slot": "pants",
        "label": "Green Pants",
        "cost": 0,
        "emoji": "👖",
        "color": "#4b974b",
        "accent": "#3a7a3a",
        "pattern": "solid",
        "badge": "",
        "blurb": "Classic starter pants",
    },
    {
        "id": "pants_blue",
        "slot": "pants",
        "label": "Blue Pants",
        "cost": 40,
        "emoji": "👖",
        "color": "#0d69ac",
        "accent": "#0a4f82",
        "pattern": "solid",
        "badge": "",
        "blurb": "Bright blue jeans",
    },
    {
        "id": "pants_black",
        "slot": "pants",
        "label": "Black Pants",
        "cost": 50,
        "emoji": "👖",
        "color": "#1e293b",
        "accent": "#0f172a",
        "pattern": "solid",
        "badge": "",
        "blurb": "Tryhard black",
    },
    {
        "id": "pants_gray",
        "slot": "pants",
        "label": "Gray Pants",
        "cost": 50,
        "emoji": "👖",
        "color": "#64748b",
        "accent": "#334155",
        "pattern": "solid",
        "badge": "",
        "blurb": "Stealth gray",
    },
    {
        "id": "pants_red",
        "slot": "pants",
        "label": "Red Pants",
        "cost": 60,
        "emoji": "👖",
        "color": "#c41c1c",
        "accent": "#7f1d1d",
        "pattern": "solid",
        "badge": "",
        "blurb": "Hot red pants",
    },
    {
        "id": "pants_white",
        "slot": "pants",
        "label": "White Pants",
        "cost": 80,
        "emoji": "👖",
        "color": "#f1f5f9",
        "accent": "#cbd5e1",
        "pattern": "solid",
        "badge": "",
        "blurb": "Clean white",
    },
    {
        "id": "pants_camo",
        "slot": "pants",
        "label": "Camo Pants",
        "cost": 200,
        "emoji": "🪖",
        "color": "#3f6212",
        "accent": "#a3e635",
        "pattern": "dots",
        "badge": "",
        "blurb": "Hide on the map",
    },
    {
        "id": "pants_stripe",
        "slot": "pants",
        "label": "Stripe Pants",
        "cost": 180,
        "emoji": "👖",
        "color": "#1e3a8a",
        "accent": "#93c5fd",
        "pattern": "stripe",
        "badge": "",
        "blurb": "Sporty stripes",
    },
    {
        "id": "pants_gold",
        "slot": "pants",
        "label": "Gold Pants",
        "cost": 6000,
        "emoji": "✨",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "gold",
        "badge": "",
        "blurb": "Match the Million Shirt",
        "legendary": True,
    },
    {
        "id": "pants_arena",
        "slot": "pants",
        "label": "Arena Pants",
        "cost": 900,
        "emoji": "🏟️",
        "color": "#111827",
        "accent": "#22c55e",
        "pattern": "stripe",
        "badge": "",
        "blurb": "Rivals arena fit",
    },
    # High tier — all under 1B (Admin stays the cap)
    {
        "id": "tee_nebula",
        "slot": "shirt",
        "label": "Nebula Shirt",
        "cost": 100_000,
        "emoji": "🌌",
        "color": "#312e81",
        "accent": "#c084fc",
        "pattern": "dots",
        "badge": "🌌",
        "blurb": "Space clouds — 100K coins",
        "legendary": True,
    },
    {
        "id": "tee_void",
        "slot": "shirt",
        "label": "Void Shirt",
        "cost": 250_000,
        "emoji": "⬛",
        "color": "#020617",
        "accent": "#38bdf8",
        "pattern": "admin",
        "badge": "◆",
        "blurb": "Deep black — 250K coins",
        "legendary": True,
    },
    {
        "id": "tee_galaxy",
        "slot": "shirt",
        "label": "Galaxy Shirt",
        "cost": 500_000,
        "emoji": "🪐",
        "color": "#1e1b4b",
        "accent": "#f472b6",
        "pattern": "rainbow",
        "badge": "🪐",
        "blurb": "Whole galaxy on your chest — 500K",
        "legendary": True,
    },
    {
        "id": "tee_legend",
        "slot": "shirt",
        "label": "Legend Shirt",
        "cost": 2_000_000,
        "emoji": "🏅",
        "color": "#7c2d12",
        "accent": "#fbbf24",
        "pattern": "gold",
        "badge": "2M",
        "blurb": "2 million coins",
        "legendary": True,
    },
    {
        "id": "tee_champion",
        "slot": "shirt",
        "label": "Champion Shirt",
        "cost": 5_000_000,
        "emoji": "🥇",
        "color": "#1d4ed8",
        "accent": "#fde68a",
        "pattern": "gold",
        "badge": "5M",
        "blurb": "5 million coins",
        "legendary": True,
    },
    {
        "id": "tee_titan",
        "slot": "shirt",
        "label": "Titan Shirt",
        "cost": 10_000_000,
        "emoji": "🗿",
        "color": "#334155",
        "accent": "#f8fafc",
        "pattern": "stripe",
        "badge": "10M",
        "blurb": "10 million coins",
        "legendary": True,
    },
    {
        "id": "tee_eternal",
        "slot": "shirt",
        "label": "Eternal Shirt",
        "cost": 25_000_000,
        "emoji": "♾️",
        "color": "#0f172a",
        "accent": "#22d3ee",
        "pattern": "dots",
        "badge": "25M",
        "blurb": "25 million coins",
        "legendary": True,
    },
    {
        "id": "tee_cosmic",
        "slot": "shirt",
        "label": "Cosmic Shirt",
        "cost": 50_000_000,
        "emoji": "🌠",
        "color": "#4c1d95",
        "accent": "#38bdf8",
        "pattern": "rainbow",
        "badge": "50M",
        "blurb": "50 million coins",
        "legendary": True,
    },
    {
        "id": "tee_omega",
        "slot": "shirt",
        "label": "Omega Shirt",
        "cost": 100_000_000,
        "emoji": "💠",
        "color": "#0b0618",
        "accent": "#e879f9",
        "pattern": "admin",
        "badge": "100M",
        "blurb": "100 million coins",
        "legendary": True,
    },
    {
        "id": "tee_nova",
        "slot": "shirt",
        "label": "Nova Shirt",
        "cost": 250_000_000,
        "emoji": "💥",
        "color": "#7f1d1d",
        "accent": "#fbbf24",
        "pattern": "gold",
        "badge": "250M",
        "blurb": "250 million coins",
        "legendary": True,
    },
    {
        "id": "tee_infinity",
        "slot": "shirt",
        "label": "Infinity Shirt",
        "cost": 500_000_000,
        "emoji": "✨",
        "color": "#082f49",
        "accent": "#a5f3fc",
        "pattern": "gold",
        "badge": "500M",
        "blurb": "500 million coins",
        "legendary": True,
    },
    {
        "id": "tee_nearadmin",
        "slot": "shirt",
        "label": "Apex Shirt",
        "cost": 999_000_000,
        "emoji": "⭐",
        "color": "#111827",
        "accent": "#fbbf24",
        "pattern": "gold",
        "badge": "999M",
        "blurb": "Just under 1B — 999 million coins",
        "legendary": True,
    },
    {
        "id": "pants_void",
        "slot": "pants",
        "label": "Void Pants",
        "cost": 250_000,
        "emoji": "⬛",
        "color": "#020617",
        "accent": "#38bdf8",
        "pattern": "admin",
        "badge": "",
        "blurb": "250K coins",
        "legendary": True,
    },
    {
        "id": "pants_million",
        "slot": "pants",
        "label": "Million Pants",
        "cost": 1_000_000,
        "emoji": "🏆",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "gold",
        "badge": "",
        "blurb": "1 million coins",
        "legendary": True,
    },
    {
        "id": "pants_titan",
        "slot": "pants",
        "label": "Titan Pants",
        "cost": 10_000_000,
        "emoji": "🗿",
        "color": "#334155",
        "accent": "#f8fafc",
        "pattern": "stripe",
        "badge": "",
        "blurb": "10 million coins",
        "legendary": True,
    },
    {
        "id": "pants_omega",
        "slot": "pants",
        "label": "Omega Pants",
        "cost": 100_000_000,
        "emoji": "💠",
        "color": "#0b0618",
        "accent": "#e879f9",
        "pattern": "admin",
        "badge": "",
        "blurb": "100 million coins",
        "legendary": True,
    },
    {
        "id": "pants_infinity",
        "slot": "pants",
        "label": "Infinity Pants",
        "cost": 500_000_000,
        "emoji": "✨",
        "color": "#082f49",
        "accent": "#a5f3fc",
        "pattern": "gold",
        "badge": "",
        "blurb": "500 million coins",
        "legendary": True,
    },
    {
        "id": "pants_nearadmin",
        "slot": "pants",
        "label": "Apex Pants",
        "cost": 999_000_000,
        "emoji": "⭐",
        "color": "#111827",
        "accent": "#fbbf24",
        "pattern": "gold",
        "badge": "",
        "blurb": "Just under 1B — 999 million coins",
        "legendary": True,
    },
    {
        "id": "acc_halo",
        "slot": "hat",
        "label": "Halo",
        "cost": 2_000_000,
        "emoji": "😇",
        "color": "#fde68a",
        "accent": "#fbbf24",
        "pattern": "hat",
        "badge": "",
        "blurb": "2 million coins",
        "legendary": True,
        "place": "head",
    },
    {
        "id": "acc_meteor",
        "slot": "hat",
        "label": "Meteor Pack",
        "cost": 10_000_000,
        "emoji": "☄️",
        "color": "#9a3412",
        "accent": "#fb923c",
        "pattern": "hat",
        "badge": "",
        "blurb": "10 million coins",
        "legendary": True,
        "place": "back",
    },
    {
        "id": "acc_blackhole",
        "slot": "hat",
        "label": "Black Hole",
        "cost": 50_000_000,
        "emoji": "🕳️",
        "color": "#020617",
        "accent": "#818cf8",
        "pattern": "hat",
        "badge": "",
        "blurb": "50 million coins",
        "legendary": True,
        "place": "back",
    },
    {
        "id": "acc_omega",
        "slot": "hat",
        "label": "Omega Visor",
        "cost": 100_000_000,
        "emoji": "🧿",
        "color": "#0b0618",
        "accent": "#e879f9",
        "pattern": "hat",
        "badge": "",
        "blurb": "100 million coins",
        "legendary": True,
        "place": "face",
    },
    {
        "id": "acc_infinity",
        "slot": "hat",
        "label": "Infinity Ring",
        "cost": 500_000_000,
        "emoji": "💫",
        "color": "#082f49",
        "accent": "#a5f3fc",
        "pattern": "hat",
        "badge": "",
        "blurb": "500 million coins",
        "legendary": True,
        "place": "head",
    },
    {
        "id": "acc_nearadmin",
        "slot": "hat",
        "label": "Apex Halo",
        "cost": 999_000_000,
        "emoji": "🌟",
        "color": "#111827",
        "accent": "#fbbf24",
        "pattern": "hat",
        "badge": "",
        "blurb": "Just under 1B — 999 million coins",
        "legendary": True,
        "place": "head",
    },
    {
        "id": "tee_admin",
        "slot": "shirt",
        "label": "Admin Shirt",
        "cost": ADMIN_COST,
        "emoji": "⚡",
        "color": "#0b0618",
        "accent": "#c084fc",
        "pattern": "admin",
        "badge": "⚡",
        "blurb": "Owner Admin shirt — 1Q coins. Aura pours off this shirt. Only 2 players in the whole game can buy Admin gear.",
        "legendary": True,
        "admin_set": True,
        "aura": True,
        "owner_limit": ADMIN_OWNER_LIMIT,
    },
    {
        "id": "pants_admin",
        "slot": "pants",
        "label": "Admin Pants",
        "cost": ADMIN_COST,
        "emoji": "⚡",
        "color": "#0b0618",
        "accent": "#a78bfa",
        "pattern": "admin",
        "badge": "",
        "blurb": "Owner Admin pants — 1Q coins. Aura trails from the legs. Only 2 players can own this set.",
        "legendary": True,
        "admin_set": True,
        "aura": True,
        "owner_limit": ADMIN_OWNER_LIMIT,
    },
    {
        "id": "acc_admin",
        "slot": "hat",
        "label": "Admin Crown",
        "cost": ADMIN_COST,
        "emoji": "👑",
        "color": "#c084fc",
        "accent": "#fde68a",
        "pattern": "hat",
        "badge": "",
        "blurb": "Owner Admin crown — 1Q coins. Aura bursts from the crown. Only 2 players can buy it.",
        "legendary": True,
        "admin_set": True,
        "aura": True,
        "owner_limit": ADMIN_OWNER_LIMIT,
        "place": "head",
    },
    # Name animations — default is simple; the rest are bought
    {
        "id": "name_plain",
        "slot": "name",
        "label": "Simple Name",
        "cost": 0,
        "emoji": "Aa",
        "color": "#0f172a",
        "accent": "#64748b",
        "pattern": "name",
        "badge": "",
        "blurb": "Your name, written simply — free!",
        "anim": "plain",
    },
    {
        "id": "name_bounce",
        "slot": "name",
        "label": "Bounce Name",
        "cost": 80,
        "emoji": "🎈",
        "color": "#7c3aed",
        "accent": "#c4b5fd",
        "pattern": "name",
        "badge": "",
        "blurb": "Your name bounces up and down",
        "anim": "bounce",
    },
    {
        "id": "name_wave",
        "slot": "name",
        "label": "Wave Name",
        "cost": 150,
        "emoji": "🌊",
        "color": "#0284c7",
        "accent": "#7dd3fc",
        "pattern": "name",
        "badge": "",
        "blurb": "Each letter waves hello",
        "anim": "wave",
    },
    {
        "id": "name_glow",
        "slot": "name",
        "label": "Glow Name",
        "cost": 250,
        "emoji": "✨",
        "color": "#a78bfa",
        "accent": "#ddd6fe",
        "pattern": "name",
        "badge": "",
        "blurb": "Soft glow around your name",
        "anim": "glow",
    },
    {
        "id": "name_rainbow",
        "slot": "name",
        "label": "Rainbow Name",
        "cost": 400,
        "emoji": "🌈",
        "color": "#ec4899",
        "accent": "#22d3ee",
        "pattern": "name",
        "badge": "",
        "blurb": "Rainbow colors slide across your name",
        "anim": "rainbow",
    },
    {
        "id": "name_sparkle",
        "slot": "name",
        "label": "Sparkle Name",
        "cost": 600,
        "emoji": "🌟",
        "color": "#f59e0b",
        "accent": "#fde68a",
        "pattern": "name",
        "badge": "",
        "blurb": "Letters twinkle like stars",
        "anim": "sparkle",
    },
    {
        "id": "name_neon",
        "slot": "name",
        "label": "Neon Name",
        "cost": 900,
        "emoji": "💡",
        "color": "#22d3ee",
        "accent": "#a3e635",
        "pattern": "name",
        "badge": "",
        "blurb": "Bright neon sign name",
        "anim": "neon",
    },
    {
        "id": "name_gold",
        "slot": "name",
        "label": "Gold Name",
        "cost": 1500,
        "emoji": "🥇",
        "color": "#f59e0b",
        "accent": "#b45309",
        "pattern": "name",
        "badge": "",
        "blurb": "Shiny gold letters",
        "anim": "gold",
        "legendary": True,
    },
    {
        "id": "name_fire",
        "slot": "name",
        "label": "Fire Name",
        "cost": 2500,
        "emoji": "🔥",
        "color": "#ef4444",
        "accent": "#f59e0b",
        "pattern": "name",
        "badge": "",
        "blurb": "Your name burns like fire",
        "anim": "fire",
        "legendary": True,
    },
    {
        "id": "name_apex",
        "slot": "name",
        "label": "Apex Shine",
        "cost": 10000,
        "emoji": "⚡",
        "color": "#c084fc",
        "accent": "#fde68a",
        "pattern": "name",
        "badge": "",
        "blurb": "Owner-style shine on your Apex ID",
        "anim": "apex",
        "legendary": True,
    },
)

SHOP_BY_ID = {item["id"]: item for item in MARKET_ITEMS}


def get_item(item_id: str | None) -> dict | None:
    if not item_id:
        return None
    return SHOP_BY_ID.get(str(item_id).strip())


def items_for_slot(slot: str) -> list[dict]:
    return [item for item in MARKET_ITEMS if item["slot"] == slot]


def cost_label(cost: int) -> str:
    n = int(cost)
    if n >= 1_000_000_000_000_000:
        q = n // 1_000_000_000_000_000
        return f"{q}Q"
    if n >= 1_000_000_000_000:
        return f"{n // 1_000_000_000_000}T"
    if n >= 1_000_000_000:
        return f"{n // 1_000_000_000}B"
    if n >= 1_000_000:
        return f"{n // 1_000_000}M"
    if n >= 1_000:
        return f"{n // 1_000}K"
    return str(n)


def item_public(item: dict) -> dict:
    place = item.get("place") or ("head" if item["slot"] == "hat" else "body")
    cost = int(item["cost"])
    return {
        "id": item["id"],
        "slot": item["slot"],
        "label": item["label"],
        "cost": cost,
        "cost_label": cost_label(cost),
        "emoji": item["emoji"],
        "color": item["color"],
        "accent": item["accent"],
        "pattern": item["pattern"],
        "badge": item.get("badge") or "",
        "blurb": item.get("blurb") or "",
        "legendary": bool(item.get("legendary")),
        "place": place,
        "admin_set": bool(item.get("admin_set")),
        "aura": bool(item.get("aura")),
        "owner_limit": int(item["owner_limit"]) if item.get("owner_limit") else 0,
        "anim": item.get("anim") or "",
    }


def name_style(item_id: str | None) -> str:
    item = get_item(item_id)
    if item and item.get("slot") == "name" and item.get("anim"):
        return str(item["anim"])
    return "plain"
